name: Dev Test and Deploy

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Test Music Artist Album Search Applicaiton
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
        
      - name: Allowing legacy dependencies
        run: npm config set legacy-peer-deps true

      - name: Install Dependencies    
        run: npm ci

      - name: Running Tests
        run: npm run test
    

  build:
    name: Build Music Artist Album Search Application
    runs-on: ubuntu-latest
    environment: production

    needs: test

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
        
      - name: Allowing legacy dependencies
        run: npm config set legacy-peer-deps true

      - name: Install Dependencies    
        run: npm ci

      - name: Building the project
        run: npm run build

      - name: Deploy to my Lightsail instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/var/www/html/music-artist-album-search-dev"

